export interface Denomination {
  amount: string;
  price: number;
  label: string;
}

export interface Game {
  name: string;
  slug: string;
  developer: string;
  image: string;
  description: string;
  denominations: Denomination[];
}

export const games: Game[] = [
  {
    name: "Mobile Legends",
    slug: "mobile-legends",
    developer: "Moonton",
    image: "/games/mobile-legends.jpg",
    description: "Diamond Top Up",
    denominations: [
      { amount: "86 Diamonds", price: 19000, label: "86 💎" },
      { amount: "172 Diamonds", price: 38000, label: "172 💎" },
      { amount: "257 Diamonds", price: 57000, label: "257 💎" },
      { amount: "344 Diamonds", price: 76000, label: "344 💎" },
      { amount: "514 Diamonds", price: 114000, label: "514 💎" },
      { amount: "706 Diamonds", price: 152000, label: "706 💎" },
    ],
  },
  {
    name: "Mobile Legends Paket Irit",
    slug: "mobile-legends-paket-irit",
    developer: "Moonton",
    image: "/games/mobile-legends-paket-irit.jpg",
    description: "Paket Irit Diamond",
    denominations: [
      { amount: "86 Diamonds", price: 18000, label: "86 💎" },
      { amount: "172 Diamonds", price: 36000, label: "172 💎" },
      { amount: "257 Diamonds", price: 54000, label: "257 💎" },
    ],
  },
  {
    name: "Free Fire",
    slug: "free-fire",
    developer: "Garena",
    image: "/games/free-fire.jpg",
    description: "Diamond Top Up",
    denominations: [
      { amount: "70 Diamonds", price: 15000, label: "70 💎" },
      { amount: "140 Diamonds", price: 29000, label: "140 💎" },
      { amount: "355 Diamonds", price: 69000, label: "355 💎" },
      { amount: "720 Diamonds", price: 139000, label: "720 💎" },
      { amount: "1450 Diamonds", price: 279000, label: "1450 💎" },
    ],
  },
  {
    name: "Free Fire MAX",
    slug: "free-fire-max",
    developer: "Garena",
    image: "/games/free-fire-max.jpg",
    description: "Diamond Top Up",
    denominations: [
      { amount: "70 Diamonds", price: 15000, label: "70 💎" },
      { amount: "140 Diamonds", price: 29000, label: "140 💎" },
      { amount: "355 Diamonds", price: 69000, label: "355 💎" },
      { amount: "720 Diamonds", price: 139000, label: "720 💎" },
    ],
  },
  {
    name: "PUBG Mobile",
    slug: "pubg-mobile",
    developer: "Tencent Games",
    image: "/games/pubg-mobile.png",
    description: "UC Top Up",
    denominations: [
      { amount: "60 UC", price: 15000, label: "60 UC" },
      { amount: "325 UC", price: 75000, label: "325 UC" },
      { amount: "660 UC", price: 149000, label: "660 UC" },
      { amount: "1800 UC", price: 379000, label: "1800 UC" },
    ],
  },
  {
    name: "Valorant",
    slug: "valorant",
    developer: "Riot Games",
    image: "/games/valorant.jpg",
    description: "VP Top Up",
    denominations: [
      { amount: "125 VP", price: 15000, label: "125 VP" },
      { amount: "420 VP", price: 49000, label: "420 VP" },
      { amount: "700 VP", price: 79000, label: "700 VP" },
      { amount: "1375 VP", price: 149000, label: "1375 VP" },
      { amount: "2400 VP", price: 249000, label: "2400 VP" },
    ],
  },
  {
    name: "Genshin Impact",
    slug: "genshin-impact",
    developer: "HoYoverse",
    image: "/games/genshin-impact.jpg",
    description: "Genesis Crystal Top Up",
    denominations: [
      { amount: "60 Crystals", price: 16000, label: "60 💠" },
      { amount: "330 Crystals", price: 79000, label: "330 💠" },
      { amount: "1090 Crystals", price: 249000, label: "1090 💠" },
      { amount: "2240 Crystals", price: 479000, label: "2240 💠" },
      { amount: "3880 Crystals", price: 799000, label: "3880 💠" },
    ],
  },
  {
    name: "Honkai Star Rail",
    slug: "honkai-star-rail",
    developer: "HoYoverse",
    image: "/games/honkai-star-rail.jpg",
    description: "Oneiric Shard Top Up",
    denominations: [
      { amount: "60 Shards", price: 16000, label: "60 ✨" },
      { amount: "330 Shards", price: 79000, label: "330 ✨" },
      { amount: "1090 Shards", price: 249000, label: "1090 ✨" },
      { amount: "2240 Shards", price: 479000, label: "2240 ✨" },
      { amount: "3880 Shards", price: 799000, label: "3880 ✨" },
    ],
  },
  {
    name: "ROBLOX",
    slug: "roblox",
    developer: "Roblox Corporation",
    image: "/games/roblox.jpg",
    description: "Robux Top Up",
    denominations: [
      { amount: "80 Robux", price: 15000, label: "80 R$" },
      { amount: "200 Robux", price: 35000, label: "200 R$" },
      { amount: "400 Robux", price: 69000, label: "400 R$" },
      { amount: "800 Robux", price: 135000, label: "800 R$" },
      { amount: "1700 Robux", price: 269000, label: "1700 R$" },
    ],
  },
  {
    name: "Mobile Legends Global",
    slug: "mobile-legends-global",
    developer: "Moonton",
    image: "/games/mobile-legends-global.jpg",
    description: "Diamond Global Server",
    denominations: [
      { amount: "86 Diamonds", price: 20000, label: "86 💎" },
      { amount: "172 Diamonds", price: 40000, label: "172 💎" },
      { amount: "257 Diamonds", price: 60000, label: "257 💎" },
    ],
  },
  {
    name: "Magic Chess Go Go",
    slug: "magic-chess-go-go",
    developer: "Vizta Games",
    image: "/games/magic-chess-go-go.jpg",
    description: "Diamond Top Up",
    denominations: [
      { amount: "86 Diamonds", price: 19000, label: "86 💎" },
      { amount: "172 Diamonds", price: 38000, label: "172 💎" },
    ],
  },
  {
    name: "Blood Strike",
    slug: "blood-strike",
    developer: "Wizard Games",
    image: "/games/blood-strike.jpg",
    description: "Gold Top Up",
    denominations: [
      { amount: "60 Gold", price: 15000, label: "60 🪙" },
      { amount: "325 Gold", price: 75000, label: "325 🪙" },
      { amount: "660 Gold", price: 149000, label: "660 🪙" },
    ],
  },
  {
    name: "Call of Duty Mobile",
    slug: "call-of-duty-mobile",
    developer: "Garena",
    image: "/games/call-of-duty-mobile.jpg",
    description: "CP Top Up",
    denominations: [
      { amount: "80 CP", price: 15000, label: "80 CP" },
      { amount: "400 CP", price: 69000, label: "400 CP" },
      { amount: "880 CP", price: 149000, label: "880 CP" },
      { amount: "2400 CP", price: 379000, label: "2400 CP" },
    ],
  },
  {
    name: "Delta Force Garena",
    slug: "delta-force-garena",
    developer: "Garena",
    image: "/games/delta-force-garena.jpg",
    description: "Token Top Up",
    denominations: [
      { amount: "60 Token", price: 15000, label: "60 🎯" },
      { amount: "325 Token", price: 75000, label: "325 🎯" },
      { amount: "660 Token", price: 149000, label: "660 🎯" },
    ],
  },
  {
    name: "Delta Force Steam",
    slug: "delta-force-steam",
    developer: "Team Jade",
    image: "/games/delta-force-steam.jpg",
    description: "Token Top Up",
    denominations: [
      { amount: "60 Token", price: 15000, label: "60 🎯" },
      { amount: "325 Token", price: 75000, label: "325 🎯" },
    ],
  },
  {
    name: "Stumble Guys",
    slug: "stumble-guys",
    developer: "Kitka Games",
    image: "/games/stumble-guys.jpg",
    description: "Gems Top Up",
    denominations: [
      { amount: "250 Gems", price: 15000, label: "250 💎" },
      { amount: "1250 Gems", price: 69000, label: "1250 💎" },
      { amount: "2500 Gems", price: 135000, label: "2500 💎" },
    ],
  },
  {
    name: "Arena of Valor",
    slug: "arena-of-valor",
    developer: "Garena",
    image: "/games/arena-of-valor.jpg",
    description: "Voucher Top Up",
    denominations: [
      { amount: "90 Voucher", price: 15000, label: "90 🎫" },
      { amount: "230 Voucher", price: 35000, label: "230 🎫" },
      { amount: "470 Voucher", price: 69000, label: "470 🎫" },
      { amount: "950 Voucher", price: 135000, label: "950 🎫" },
    ],
  },
  {
    name: "Clash of Clans",
    slug: "clash-of-clans",
    developer: "Supercell",
    image: "/games/clash-of-clans.jpg",
    description: "Gems Top Up",
    denominations: [
      { amount: "80 Gems", price: 16000, label: "80 💎" },
      { amount: "500 Gems", price: 79000, label: "500 💎" },
      { amount: "1200 Gems", price: 159000, label: "1200 💎" },
      { amount: "2500 Gems", price: 319000, label: "2500 💎" },
    ],
  },
  {
    name: "Clash Royale",
    slug: "clash-royale",
    developer: "Supercell",
    image: "/games/clash-royale.jpg",
    description: "Gems Top Up",
    denominations: [
      { amount: "80 Gems", price: 16000, label: "80 💎" },
      { amount: "500 Gems", price: 79000, label: "500 💎" },
      { amount: "1200 Gems", price: 159000, label: "1200 💎" },
    ],
  },
  {
    name: "Honor of Kings",
    slug: "honor-of-kings",
    developer: "TiMi Studio",
    image: "/games/honor-of-kings.jpg",
    description: "Token Top Up",
    denominations: [
      { amount: "60 Token", price: 15000, label: "60 🪙" },
      { amount: "325 Token", price: 75000, label: "325 🪙" },
      { amount: "660 Token", price: 149000, label: "660 🪙" },
    ],
  },
  {
    name: "Zenless Zone Zero",
    slug: "zenless-zone-zero",
    developer: "HoYoverse",
    image: "/games/zenless-zone-zero.jpg",
    description: "Polychrome Top Up",
    denominations: [
      { amount: "60 Polychrome", price: 16000, label: "60 🔮" },
      { amount: "330 Polychrome", price: 79000, label: "330 🔮" },
      { amount: "1090 Polychrome", price: 249000, label: "1090 🔮" },
      { amount: "2240 Polychrome", price: 479000, label: "2240 🔮" },
    ],
  },
  {
    name: "Super Sus",
    slug: "super-sus",
    developer: "PI Studio",
    image: "/games/super-sus.jpg",
    description: "Golden Star Top Up",
    denominations: [
      { amount: "60 Stars", price: 15000, label: "60 ⭐" },
      { amount: "300 Stars", price: 69000, label: "300 ⭐" },
      { amount: "680 Stars", price: 149000, label: "680 ⭐" },
    ],
  },
  {
    name: "Tower of Fantasy",
    slug: "tower-of-fantasy",
    developer: "Level Infinite",
    image: "/games/tower-of-fantasy.jpg",
    description: "Tanium Top Up",
    denominations: [
      { amount: "60 Tanium", price: 16000, label: "60 💠" },
      { amount: "330 Tanium", price: 79000, label: "330 💠" },
      { amount: "1090 Tanium", price: 249000, label: "1090 💠" },
    ],
  },
  {
    name: "Ragnarok M",
    slug: "ragnarok-m",
    developer: "Gravity",
    image: "/games/ragnarok-m.jpg",
    description: "BCC Top Up",
    denominations: [
      { amount: "75 BCC", price: 15000, label: "75 BCC" },
      { amount: "370 BCC", price: 69000, label: "370 BCC" },
      { amount: "750 BCC", price: 135000, label: "750 BCC" },
    ],
  },
  {
    name: "Apex Legends Mobile",
    slug: "apex-legends-mobile",
    developer: "EA",
    image: "/games/apex-legends-mobile.jpg",
    description: "Coins Top Up",
    denominations: [
      { amount: "150 Coins", price: 25000, label: "150 🪙" },
      { amount: "600 Coins", price: 89000, label: "600 🪙" },
      { amount: "1200 Coins", price: 169000, label: "1200 🪙" },
    ],
  },
  {
    name: "League of Legends Wild Rift",
    slug: "league-of-legends-wild-rift",
    developer: "Riot Games",
    image: "/games/league-of-legends-wild-rift.jpg",
    description: "Wild Cores Top Up",
    denominations: [
      { amount: "125 Cores", price: 15000, label: "125 🔮" },
      { amount: "420 Cores", price: 49000, label: "420 🔮" },
      { amount: "700 Cores", price: 79000, label: "700 🔮" },
      { amount: "1375 Cores", price: 149000, label: "1375 🔮" },
    ],
  },
  {
    name: "Minecraft",
    slug: "minecraft",
    developer: "Mojang",
    image: "/games/minecraft.jpg",
    description: "Minecoins Top Up",
    denominations: [
      { amount: "320 Minecoins", price: 25000, label: "320 🪙" },
      { amount: "700 Minecoins", price: 49000, label: "700 🪙" },
      { amount: "1720 Minecoins", price: 109000, label: "1720 🪙" },
    ],
  },
  {
    name: "Point Blank",
    slug: "point-blank",
    developer: "Zepetto",
    image: "/games/point-blank.jpg",
    description: "Cash Top Up",
    denominations: [
      { amount: "1200 Cash", price: 15000, label: "1200 💰" },
      { amount: "6000 Cash", price: 69000, label: "6000 💰" },
      { amount: "12000 Cash", price: 135000, label: "12000 💰" },
    ],
  },
  {
    name: "Undawn",
    slug: "undawn",
    developer: "Garena",
    image: "/games/undawn.jpg",
    description: "RC Top Up",
    denominations: [
      { amount: "60 RC", price: 16000, label: "60 🪙" },
      { amount: "325 RC", price: 79000, label: "325 🪙" },
      { amount: "660 RC", price: 149000, label: "660 🪙" },
    ],
  },
  {
    name: "Steam Wallet",
    slug: "steam-wallet",
    developer: "Valve",
    image: "/games/steam-wallet.svg",
    description: "Wallet Code",
    denominations: [
      { amount: "IDR 45.000", price: 47000, label: "45rb" },
      { amount: "IDR 60.000", price: 63000, label: "60rb" },
      { amount: "IDR 90.000", price: 94000, label: "90rb" },
      { amount: "IDR 120.000", price: 125000, label: "120rb" },
      { amount: "IDR 250.000", price: 260000, label: "250rb" },
    ],
  },
  {
    name: "Google Play",
    slug: "google-play",
    developer: "Google",
    image: "/games/google-play.svg",
    description: "Gift Card",
    denominations: [
      { amount: "IDR 20.000", price: 21000, label: "20rb" },
      { amount: "IDR 50.000", price: 52000, label: "50rb" },
      { amount: "IDR 100.000", price: 103000, label: "100rb" },
      { amount: "IDR 150.000", price: 155000, label: "150rb" },
      { amount: "IDR 300.000", price: 310000, label: "300rb" },
    ],
  },
  {
    name: "Garena Shells",
    slug: "garena-shells",
    developer: "Garena",
    image: "/games/garena-shells.svg",
    description: "Shells Top Up",
    denominations: [
      { amount: "33 Shells", price: 5000, label: "33 🐚" },
      { amount: "66 Shells", price: 10000, label: "66 🐚" },
      { amount: "165 Shells", price: 25000, label: "165 🐚" },
      { amount: "330 Shells", price: 50000, label: "330 🐚" },
    ],
  },
  {
    name: "Higgs Domino",
    slug: "higgs-domino",
    developer: "Higgs Games",
    image: "/games/higgs-domino.svg",
    description: "Chip Top Up",
    denominations: [
      { amount: "1B Chip", price: 15000, label: "1B 🎰" },
      { amount: "3B Chip", price: 42000, label: "3B 🎰" },
      { amount: "5B Chip", price: 69000, label: "5B 🎰" },
      { amount: "10B Chip", price: 135000, label: "10B 🎰" },
    ],
  },
  {
    name: "Wuthering Waves",
    slug: "wuthering-waves",
    developer: "Kuro Games",
    image: "/games/wuthering-waves.svg",
    description: "Lunite Top Up",
    denominations: [
      { amount: "60 Lunite", price: 16000, label: "60 🌙" },
      { amount: "330 Lunite", price: 79000, label: "330 🌙" },
      { amount: "1090 Lunite", price: 249000, label: "1090 🌙" },
      { amount: "2240 Lunite", price: 479000, label: "2240 🌙" },
    ],
  },
  {
    name: "NIKKE",
    slug: "nikke",
    developer: "Level Infinite",
    image: "/games/nikke.svg",
    description: "Gem Top Up",
    denominations: [
      { amount: "60 Gems", price: 16000, label: "60 💎" },
      { amount: "330 Gems", price: 79000, label: "330 💎" },
      { amount: "1090 Gems", price: 249000, label: "1090 💎" },
    ],
  },
  {
    name: "Identity V",
    slug: "identity-v",
    developer: "NetEase",
    image: "/games/identity-v.svg",
    description: "Echoes Top Up",
    denominations: [
      { amount: "60 Echoes", price: 16000, label: "60 🔊" },
      { amount: "330 Echoes", price: 79000, label: "330 🔊" },
      { amount: "1090 Echoes", price: 249000, label: "1090 🔊" },
    ],
  },
  {
    name: "ML Adventure",
    slug: "mobile-legends-adventure",
    developer: "Moonton",
    image: "/games/mobile-legends-adventure.svg",
    description: "Diamond Top Up",
    denominations: [
      { amount: "86 Diamonds", price: 19000, label: "86 💎" },
      { amount: "172 Diamonds", price: 38000, label: "172 💎" },
      { amount: "514 Diamonds", price: 114000, label: "514 💎" },
    ],
  },
  {
    name: "Lords Mobile",
    slug: "lords-mobile",
    developer: "IGG",
    image: "/games/lords-mobile.svg",
    description: "Diamonds Top Up",
    denominations: [
      { amount: "65 Diamonds", price: 16000, label: "65 💎" },
      { amount: "260 Diamonds", price: 59000, label: "260 💎" },
      { amount: "650 Diamonds", price: 139000, label: "650 💎" },
    ],
  },
  {
    name: "LifeAfter",
    slug: "life-after",
    developer: "NetEase",
    image: "/games/life-after.svg",
    description: "Credits Top Up",
    denominations: [
      { amount: "60 Credits", price: 16000, label: "60 🪙" },
      { amount: "330 Credits", price: 79000, label: "330 🪙" },
      { amount: "660 Credits", price: 149000, label: "660 🪙" },
    ],
  },
  {
    name: "Eggy Party",
    slug: "eggy-party",
    developer: "NetEase",
    image: "/games/eggy-party.svg",
    description: "Eggy Coins Top Up",
    denominations: [
      { amount: "60 Coins", price: 16000, label: "60 🥚" },
      { amount: "330 Coins", price: 79000, label: "330 🥚" },
      { amount: "660 Coins", price: 149000, label: "660 🥚" },
    ],
  },
  {
    name: "Sausage Man",
    slug: "sausage-man",
    developer: "XD Entertainment",
    image: "/games/sausage-man.svg",
    description: "Candy Top Up",
    denominations: [
      { amount: "60 Candy", price: 15000, label: "60 🍬" },
      { amount: "300 Candy", price: 69000, label: "300 🍬" },
      { amount: "680 Candy", price: 149000, label: "680 🍬" },
    ],
  },
  {
    name: "Naraka Bladepoint",
    slug: "naraka-bladepoint",
    developer: "NetEase",
    image: "/games/naraka-bladepoint.svg",
    description: "Gold Top Up",
    denominations: [
      { amount: "60 Gold", price: 16000, label: "60 🪙" },
      { amount: "330 Gold", price: 79000, label: "330 🪙" },
      { amount: "1090 Gold", price: 249000, label: "1090 🪙" },
    ],
  },
  {
    name: "Ace Racer",
    slug: "ace-racer",
    developer: "NetEase",
    image: "/games/ace-racer.svg",
    description: "Crystals Top Up",
    denominations: [
      { amount: "60 Crystals", price: 16000, label: "60 💠" },
      { amount: "330 Crystals", price: 79000, label: "330 💠" },
      { amount: "660 Crystals", price: 149000, label: "660 💠" },
    ],
  },
  {
    name: "Dragon Raja",
    slug: "dragon-raja",
    developer: "Archosaur Games",
    image: "/games/dragon-raja.svg",
    description: "Coins Top Up",
    denominations: [
      { amount: "60 Coins", price: 16000, label: "60 🪙" },
      { amount: "330 Coins", price: 79000, label: "330 🪙" },
      { amount: "660 Coins", price: 149000, label: "660 🪙" },
    ],
  },
  {
    name: "One Punch Man",
    slug: "one-punch-man",
    developer: "Crunchyroll Games",
    image: "/games/one-punch-man.svg",
    description: "Gems Top Up",
    denominations: [
      { amount: "60 Gems", price: 16000, label: "60 💎" },
      { amount: "330 Gems", price: 79000, label: "330 💎" },
      { amount: "660 Gems", price: 149000, label: "660 💎" },
    ],
  },
];

export function getGameBySlug(slug: string): Game | undefined {
  return games.find((game) => game.slug === slug);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(price);
}
